spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ims?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    password:

logging:
  level:
    com.pixelstack.ims: debug
    root: info

file:
  upload:
    path: /data/ims/upload/dev/
    url-prefix: http://localhost:8080/api/files/